# Run Jobs
jobs:
  build:
    docker:
      - image: nextflow/nextflow
    environment:
      PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run:
          name: Clone Github Repo
          command: |
            cd $HOME
            git clone https://github.com/jimmyliu1326/tCANS.git
      - run:
          name: Setup environment
          command: |
            apt-get update -y && apt-get install -y curl
      - run:
          name: Run Tests
          command: |
            nextflow run tCANS/tCANS.nf --help