# Run Jobs
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    environment:
      PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            apt-get update -y && apt-get install -y git wget
            wget -qO- get.nextflow.io | bash
            chmod +x nextflow
            sudo mv nextflow /usr/local/bin/
      - run:
          name: Clone Github Repo
          command: |
            cd $HOME
            git clone https://github.com/jimmyliu1326/tCANS.git
      - run:
          name: Run Tests
          command: |
            nextflow run tCANS/tCANS.nf --help