# Run Jobs
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            conda install -y -c conda-forge -c bioconda nextflow=21.10.6
      - run:
          name: Pull nextflow workflow
          command: |
            nextflow pull -hub github jimmyliu1326/tCANS
      - run:
          name: Run Tests
          command: |
            nextflow run jimmyliu1326/tCANS --help