# Run Jobs
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            conda install -y -c conda-forge nextflow=21.10.6
      - run:
          name: Clone Github Repo
          command: |
            cd $HOME
            git clone https://github.com/jimmyliu1326/tCANS.git
      - run:
          name: Run Tests
          command: |
            cd $HOME/tCANS
            nextflow run tCANS.nf --help